// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACL6SJ3DIt77DAW8VRVz28Jl7hpUrO6qo',
    appId: '1:674234163098:web:078b778041ab1062046423',
    messagingSenderId: '674234163098',
    projectId: 'rngs-a533d',
    authDomain: 'rngs-a533d.firebaseapp.com',
    storageBucket: 'rngs-a533d.firebasestorage.app',
    measurementId: 'G-F4RSQNHSM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfWIkuSAUBXxmUO4xjXFTcRjsozf3sqgI',
    appId: '1:674234163098:android:e92cc95630e3306d046423',
    messagingSenderId: '674234163098',
    projectId: 'rngs-a533d',
    storageBucket: 'rngs-a533d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTPoLv-W9CrCzXBUQZqNGuqXj4YK-qSlM',
    appId: '1:674234163098:ios:508a0bab93429004046423',
    messagingSenderId: '674234163098',
    projectId: 'rngs-a533d',
    storageBucket: 'rngs-a533d.firebasestorage.app',
    iosBundleId: 'com.example.rngs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTPoLv-W9CrCzXBUQZqNGuqXj4YK-qSlM',
    appId: '1:674234163098:ios:508a0bab93429004046423',
    messagingSenderId: '674234163098',
    projectId: 'rngs-a533d',
    storageBucket: 'rngs-a533d.firebasestorage.app',
    iosBundleId: 'com.example.rngs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACL6SJ3DIt77DAW8VRVz28Jl7hpUrO6qo',
    appId: '1:674234163098:web:5948939c461c93e0046423',
    messagingSenderId: '674234163098',
    projectId: 'rngs-a533d',
    authDomain: 'rngs-a533d.firebaseapp.com',
    storageBucket: 'rngs-a533d.firebasestorage.app',
    measurementId: 'G-JEWS7LW17T',
  );
}
